spring:
  application:
    name: effective-mobile-task

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ruser
    password: rpass
    url: jdbc:mysql://localhost:3307/task-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8888